server:
  port: 8080
spring:
  application:
    name: therapeutic-session-control-backend
  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${DATA_SOURCE_DB_USER}
    password: ${DATA_SOURCE_DB_PASSWORD}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs.html

